### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by mreineck** [conda-forge/ducc0-feedstock#12]
I just realized that my package has made it to conda; nice! :-)

There are two minor things that may need fixing in the recipe, as far as I understand:
- The license identifier says "GPL-2.0-only", but it should be "GPL-2.0-or-later" (or similar, I don't know the canonical name)
- The default build script for the package compiles the C++ code with "-march=native", which is most likely not the way to go when building binary packages for download. From a first glance at the build scripts here I can't tell whether this is overridden. Just in case it's not, this should be changed.

Thanks,
  Martin

**Comment by ickc** [comment]
Thanks, Martin. Both should be fixed now.

**Comment by mreineck** [comment]
Thanks a lot!
I must admit that I originally didn't expect the package to be distributed via PyPI, Conda etc. This is why I thought I could get away with the default setting of "optimize natively for the current computer." And unlike many other packages, the performance gain from native optimization is really significant (can be up to a factor of 4  on CPUs with AVX512).
Still, it feels now as if defaulting to a portable binary may be the wiser choice. I could set "DUCC0_OPTIMIZATION=portable" as default in future versions and tell users to use "DUCC0_OPTIMIZATION=native" for optimized binaries. What do you think?

**Comment by ickc** [comment]
I think defaulting to `DUCC0_OPTIMIZATION=native` is fine. People who need to have "portable" binaries should already know they need to be careful on the target instruction sets. Documenting this in the "Install" section of the doc would help those people who need this.

Also, could the binary be compiled as fat binaries targetting both avx512 and avx2? I know that it is quite easy to do that using Intel compilers but not so sure about gcc. [This](https://stackoverflow.com/a/44479487/5769446) suggests it can be done in gcc but I'm not sure if it will be overly complicated.

**Comment by mreineck** [comment]
I'm aware of the function multiversioning capabilities in gcc, but unfortunately they don't do the trick, because gcc doesn't emulate the various preprocesor defines that depend on the target. For example, I take different code paths when `__AVX__` is #defined and when it isn't, and I can't cachieve this with the curent gcc tools (as far as I know).
While the Intel compilers certainly have come a long way in compiling modern C++, I would be very surprised if they generated good code for AMD CPUs (I'm thinking about the FMA3/FMA4 differences here), so this not really an option either.
An approach like https://pypi.org/project/compilertools/1.1.1/ certainly looks interesting, but I didn't manage to get this package to work with ducc so far. I will continue to investigate this.

**Comment by ickc** [comment]
Thanks for the info. I think the current solution is good enough for almost all use cases. It probably is nice to have if compilertools can help, but on the other hand, the one that really need a feature like that is conda (because PyPI allows sdist so you can default to optimize for the user’s computer), as it is binary distribution only.

I only mention icc because it seems to perform those dispatch with a very simple setting. I also think Intel compilers has many problems. It being proprietary making distributing it via CI complicated (probably use free beta license which is suboptimal), also the code it generates for AMD is handicapped and requires some sort of hack for it to be functioning optimally. And together with the fact that increasingly more HPC facilities including NERSC is abandoning Intel, it will not be good default.
